"""Bundled EGM96 grid data.

The ``egm96-5.npz`` grid is generated by the ``generate-egm96-grid`` script and
is **not** committed to the repository -- it is produced during the CI build and
bundled into the wheel.  See the project README for details.
"""
